### ISSUE TITLE
Remove Premium package

### ISSUE THREAD

**Issue by Nikanoras** [VismaLietuva/simoona#279]
Hey @Aleksanderis ,
I wanted to ask if it would make sense to remove separate premium project and add it to all other "free-mium" stuff, as Simoona is fully open-source now? 
Why am I asking this, is because I started to investigate build issues with project it self. When you try to build all solution, you get lots of random errors from Shrooms.Premium project. My guess for the reason is the indirect project reference. As I checked Shrooms.Premium build output is being placed in Api project Extensions folder, and that's how premium is integrated. Please correct me if I'm wrong on this part. 

Kindly,
Nikanoras

**Comment by Aleksanderis** [comment]
I would like to keep Premium features separate. Maybe the name is not correct anymore, but having these features separately kind of adds one stage of separation/modularization, and merging them back would be a step backwards.
However I think it can be changed so, that they are loaded not as extensions, but referenced as usual project reference.
It should solve project building issues.

**Comment by Nikanoras** [comment]
Will do so.

**Comment by Aleksanderis** [comment]
#284 was merged, so closing the issue.
