### ISSUE TITLE
IUnitOfWork vs IUnitOfWork2

### ISSUE THREAD

**Issue by Nikanoras** [VismaLietuva/simoona#287]
Hi,
Could you explain why do we have two UnitOfWork? Thank you.

Br,
Nikanoras

**Comment by Aleksanderis** [comment]
It's kind of a rhetorical question - "due to historical reasons".

..So feel free to leave just one, but please don't create a third one. :)

![image](https://github.com/VismaLietuva/simoona/assets/2393205/9334859f-1e97-4548-8140-885053b75be1)

**Comment by Nikanoras** [comment]
Noted :)
