### ISSUE TITLE
Migration to newer Angular

### ISSUE THREAD

**Issue by Nikanoras** [VismaLietuva/simoona#289]
Hi,
Are there any plans, or ongoing work, to migrate to new Angular?

Br,
Nikanoras

**Comment by Aleksanderis** [comment]
It was started (in an internal repository) with big general UI overhaul. There was some good progress on it, but later it was put on hold.

**Comment by Aleksanderis** [comment]
Some sneak peek:
![simoona-v2](https://github.com/VismaLietuva/simoona/assets/2393205/2f12abc4-c01e-4ff9-b63a-5391fefb0ea2)

**Comment by Nikanoras** [comment]
This is a rewrite, yes? Are you planning to make it open-source?

**Comment by Aleksanderis** [comment]
Yes, it's a rewrite, and as mentioned - it's on hold, with no clear plans so far.

**Comment by Nikanoras** [comment]
We are thinking of new features in Simoona which could be implemented. The problem I see, is that adding more features to project with legacy technologies only creates a bigger gap to update it someday to the latest stack.

I started to investigate how we could update to latest Angular version. I looked into the hybrid model of having both AngularJs and Angular. Theoretically it should be possible to migrate in such way. I tried to implement it, but with my limited knowledge in front-end tech is quite difficult.

Another option is to rewrite from scratch. It could be done as such, that both versions of Simoona UI can be up, an old one, and a beta with new UI. In that case we could evade a big boom merge, and a change. User could use both version. If new Simoona UI would be open-source, we could contribute to it.

**Comment by Aleksanderis** [comment]
Yes, adding new UI features doesn't make a lot of sense now.
We don't plan to follow any other migration way (we already were there), if we back to this topic again - most likely we will continue with the rewrite project.

We will discuss internally about possibility to contribute to the mentioned rewrite project (like possibility making it open source or any other way). However it's vacations season now, so such discussions can take some time.

**Comment by Aleksanderis** [comment]
@Nikanoras we are open to go open-source with our Simoona UI upgrade solution. But the question is how serious are ready to contribute into it, because we would like to discuss and agree on some things before going further with it?

**Comment by Nikanoras** [comment]
Hi @Aleksanderis,
At the moment, we can't guarantee a steady contribution to the project, as it solely depends on people willing to contribute on their free time.

**Comment by Aleksanderis** [comment]
In that case there is a little sense to change something, since the project is really premature, therefore needs some strong contribution and guidance from experienced front-end developers. Otherwise it will end as a ball of mud and later on it will be even harder to get contributions for it.

**Comment by Aleksanderis** [comment]
Closing as not active and having in mind there is another migration to Angular project.
